services:
  - type: web
    name: tsu-upskill-backend
    runtime: python

    rootDir: tsu-nav-project/tsu_upskill_backend

    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput

    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2

    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: tsu-upskill-backend.onrender.com
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_HOST
        fromDatabase:
          name: tsu-upskill-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: tsu-upskill-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: tsu-upskill-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tsu-upskill-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: tsu-upskill-db
          property: port
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

  - type: pserv
    name: tsu-upskill-redis
    runtime: redis

databases:
  - name: tsu-upskill-db
    engine: postgres
    version: '15'

